### ISSUE TITLE
Sketch 52.1 version is not available

### ISSUE THREAD

**Issue by SergioZhangC** [mheesakkers/sketch-plugin-convert-to-grayscale#1]
Sketch 52.1 version
No reaction after use

**Comment by mheesakkers** [comment]
Will look into this as soon as possible ;)

**Comment by mheesakkers** [comment]
@SergioZhangC I think I got it working again. If all went well you were asked to update the plugin otherwise you'll need to reinstall. Could you check if it works again then I can close the issue ;)? Thanks!

**Comment by SergioZhangC** [comment]
Thank you very much, it is already working.  👍
